// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiftySignal.AdaptiveObserverData;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NiftySignal.AdaptiveObserverData.Migrations
{
    [DbContext(typeof(AdaptiveObserverDbContext))]
    [Migration("20261008054158_AddProjectionHealthAndVersionedCommentary")]
    partial class AddProjectionHealthAndVersionedCommentary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveCommentaryEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BarSeq")
                        .HasColumnType("integer");

                    b.Property<bool>("BiasChanged")
                        .HasColumnType("boolean");

                    b.Property<string>("CommentaryVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ConfirmationEvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContradictionEvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataQualityJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventBias")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("EventIdentity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("EvidenceAgreement")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MarketRegime")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NotificationReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousBias")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long?>("PreviousEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("PrimaryEvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RenderedCommentary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("ShouldNotifyTelegram")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EventIdentity")
                        .IsUnique();

                    b.HasIndex("SessionId", "BarSeq");

                    b.HasIndex("TradeDate", "OccurredAtUtc");

                    b.HasIndex("SessionId", "EventBias", "OccurredAtUtc");

                    b.HasIndex("SessionId", "EventType", "OccurredAtUtc");

                    b.ToTable("adaptive_commentary_events", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveCommentaryNotificationJobRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("NextAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptUtc");

                    b.ToTable("adaptive_commentary_notification_jobs", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveCommentaryRuntimeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveAgreement")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ActiveBias")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ActivePhase")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("ActiveStartedBarSeq")
                        .HasColumnType("integer");

                    b.Property<string>("ActiveSupportingFamilies")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CommentaryVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CurrentBias")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long?>("CurrentEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrentEventType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CurrentLifecycle")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CurrentRegime")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("LastEvaluatedBarSeq")
                        .HasColumnType("integer");

                    b.Property<int?>("LastTelegramBarSeq")
                        .HasColumnType("integer");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CommentaryVersion")
                        .IsUnique();

                    b.ToTable("adaptive_commentary_runtime", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveFutureBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Ask")
                        .HasColumnType("double precision");

                    b.Property<long?>("AskQty")
                        .HasColumnType("bigint");

                    b.Property<double>("BarPriceDisplacement")
                        .HasColumnType("double precision");

                    b.Property<int>("BarSeq")
                        .HasColumnType("integer");

                    b.Property<double?>("Bid")
                        .HasColumnType("double precision");

                    b.Property<long?>("BidQty")
                        .HasColumnType("bigint");

                    b.Property<double?>("BookImbalance")
                        .HasColumnType("double precision");

                    b.Property<double>("Close")
                        .HasColumnType("double precision");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EndAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EnrichedBuyVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("EnrichedDelta")
                        .HasColumnType("bigint");

                    b.Property<double>("EnrichedDeltaRatio")
                        .HasColumnType("double precision");

                    b.Property<long>("EnrichedSellVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("EnrichedUnknownVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("FirstSourceTickId")
                        .HasColumnType("bigint");

                    b.Property<double>("High")
                        .HasColumnType("double precision");

                    b.Property<long>("LastSourceTickId")
                        .HasColumnType("bigint");

                    b.Property<double>("Low")
                        .HasColumnType("double precision");

                    b.Property<double?>("Microprice")
                        .HasColumnType("double precision");

                    b.Property<long?>("OiChange")
                        .HasColumnType("bigint");

                    b.Property<long?>("OiClose")
                        .HasColumnType("bigint");

                    b.Property<long?>("OiOpen")
                        .HasColumnType("bigint");

                    b.Property<double>("Open")
                        .HasColumnType("double precision");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Spread")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("StartAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("StrictBuyVolume")
                        .HasColumnType("bigint");

                    b.Property<double>("StrictCoverage")
                        .HasColumnType("double precision");

                    b.Property<long>("StrictDelta")
                        .HasColumnType("bigint");

                    b.Property<double>("StrictDeltaRatioTotal")
                        .HasColumnType("double precision");

                    b.Property<long>("StrictSellVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("StrictUnknownVolume")
                        .HasColumnType("bigint");

                    b.Property<int>("TradeUpdates")
                        .HasColumnType("integer");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<double>("Vwap")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "BarSeq")
                        .IsUnique();

                    b.HasIndex("SessionId", "EndAvailableAtUtc");

                    b.ToTable("adaptive_future_bars", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveFuturesSupplementalRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BarSeq")
                        .HasColumnType("integer");

                    b.Property<int>("BookStateChanges")
                        .HasColumnType("integer");

                    b.Property<int>("InvalidBookEvents")
                        .HasColumnType("integer");

                    b.Property<double>("InvalidBookSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("MetricsVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("MicroDevChange")
                        .HasColumnType("double precision");

                    b.Property<double?>("MicroDevEnd")
                        .HasColumnType("double precision");

                    b.Property<double?>("MicroDevStart")
                        .HasColumnType("double precision");

                    b.Property<double?>("MicroDevTimeWeighted")
                        .HasColumnType("double precision");

                    b.Property<double>("MicroDevUsableSeconds")
                        .HasColumnType("double precision");

                    b.Property<long?>("Ofi")
                        .HasColumnType("bigint");

                    b.Property<int>("OfiTransitions")
                        .HasColumnType("integer");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<double?>("TobChange")
                        .HasColumnType("double precision");

                    b.Property<double?>("TobEnd")
                        .HasColumnType("double precision");

                    b.Property<double?>("TobMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("TobMin")
                        .HasColumnType("double precision");

                    b.Property<double?>("TobStart")
                        .HasColumnType("double precision");

                    b.Property<double?>("TobTimeWeighted")
                        .HasColumnType("double precision");

                    b.Property<double>("TobUsableSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("ValidBookSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "BarSeq", "MetricsVersion")
                        .IsUnique();

                    b.ToTable("adaptive_futures_supplemental_bars", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveObserverRuntimeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CurrentPartialBarStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CurrentPartialBarVolume")
                        .HasColumnType("bigint");

                    b.Property<int>("LastCompletedBarSeq")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastProcessedSourceAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastProcessedSourceTickId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastRecoveryCompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastRecoveryReconciledBars")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastRecoveryStartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RuntimeStatus")
                        .HasColumnType("integer");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("adaptive_observer_runtime", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveOptionBandBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BandAvailable")
                        .HasColumnType("boolean");

                    b.Property<long?>("BandOiClose")
                        .HasColumnType("bigint");

                    b.Property<long?>("BandOiOpen")
                        .HasColumnType("bigint");

                    b.Property<double?>("BandPremiumIndexClose")
                        .HasColumnType("double precision");

                    b.Property<double?>("BandPremiumIndexOpen")
                        .HasColumnType("double precision");

                    b.Property<bool>("BandRolled")
                        .HasColumnType("boolean");

                    b.Property<string>("BandStrikes")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("BarBandPriceChange")
                        .HasColumnType("double precision");

                    b.Property<double?>("BarBandReturnPct")
                        .HasColumnType("double precision");

                    b.Property<long?>("BarOiChange")
                        .HasColumnType("bigint");

                    b.Property<double?>("BarOiChangePct")
                        .HasColumnType("double precision");

                    b.Property<int>("BarSeq")
                        .HasColumnType("integer");

                    b.Property<long>("BarTradeUpdates")
                        .HasColumnType("bigint");

                    b.Property<double>("CenterStrike")
                        .HasColumnType("double precision");

                    b.Property<long>("ContractEnrichedBuy")
                        .HasColumnType("bigint");

                    b.Property<long>("ContractEnrichedDelta")
                        .HasColumnType("bigint");

                    b.Property<double>("ContractEnrichedDeltaRatio")
                        .HasColumnType("double precision");

                    b.Property<long>("ContractEnrichedSell")
                        .HasColumnType("bigint");

                    b.Property<long>("ContractEnrichedUnknown")
                        .HasColumnType("bigint");

                    b.Property<double?>("ContractRollingActivityPerSecond")
                        .HasColumnType("double precision");

                    b.Property<long?>("ContractRollingEnrichedDelta")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContractRollingEnrichedDeltaChange")
                        .HasColumnType("bigint");

                    b.Property<double?>("ContractRollingEnrichedDeltaRatio")
                        .HasColumnType("double precision");

                    b.Property<long?>("ContractRollingStrictAbsDeltaChange")
                        .HasColumnType("bigint");

                    b.Property<double?>("ContractRollingStrictCoverage")
                        .HasColumnType("double precision");

                    b.Property<long?>("ContractRollingStrictDelta")
                        .HasColumnType("bigint");

                    b.Property<double?>("ContractRollingStrictDeltaRatioTotal")
                        .HasColumnType("double precision");

                    b.Property<long>("ContractStrictBuy")
                        .HasColumnType("bigint");

                    b.Property<double>("ContractStrictCoverage")
                        .HasColumnType("double precision");

                    b.Property<long>("ContractStrictDelta")
                        .HasColumnType("bigint");

                    b.Property<double>("ContractStrictDeltaRatioTotal")
                        .HasColumnType("double precision");

                    b.Property<long>("ContractStrictSell")
                        .HasColumnType("bigint");

                    b.Property<long>("ContractStrictUnknown")
                        .HasColumnType("bigint");

                    b.Property<long>("ContractTotalQuantity")
                        .HasColumnType("bigint");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EndAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("NotionalEnrichedBuy")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalEnrichedDelta")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalEnrichedDeltaRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalEnrichedSell")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalEnrichedUnknown")
                        .HasColumnType("double precision");

                    b.Property<double?>("NotionalRollingActivityPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("NotionalRollingEnrichedDelta")
                        .HasColumnType("double precision");

                    b.Property<double?>("NotionalRollingEnrichedDeltaChange")
                        .HasColumnType("double precision");

                    b.Property<double?>("NotionalRollingEnrichedDeltaRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("NotionalRollingStrictAbsDeltaChange")
                        .HasColumnType("double precision");

                    b.Property<double?>("NotionalRollingStrictCoverage")
                        .HasColumnType("double precision");

                    b.Property<double?>("NotionalRollingStrictDelta")
                        .HasColumnType("double precision");

                    b.Property<double?>("NotionalRollingStrictDeltaRatioTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalStrictBuy")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalStrictCoverage")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalStrictDelta")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalStrictDeltaRatioTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalStrictSell")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalStrictUnknown")
                        .HasColumnType("double precision");

                    b.Property<double>("NotionalTotal")
                        .HasColumnType("double precision");

                    b.Property<double?>("PremiumNotionalOiAtClose")
                        .HasColumnType("double precision");

                    b.Property<double?>("PremiumNotionalOiChange")
                        .HasColumnType("double precision");

                    b.Property<double?>("RollingBandPriceChange")
                        .HasColumnType("double precision");

                    b.Property<double?>("RollingEfficiency")
                        .HasColumnType("double precision");

                    b.Property<long?>("RollingOiChange")
                        .HasColumnType("bigint");

                    b.Property<double?>("RollingOiChangePct")
                        .HasColumnType("double precision");

                    b.Property<double?>("RollingReturnPct")
                        .HasColumnType("double precision");

                    b.Property<long?>("RollingTradeUpdates")
                        .HasColumnType("bigint");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UnavailableReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "BarSeq", "Side")
                        .IsUnique();

                    b.HasIndex("SessionId", "Side", "BarSeq");

                    b.ToTable("adaptive_option_band_bars", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveOptionResidualBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BarSeq")
                        .HasColumnType("integer");

                    b.Property<double>("CEActual")
                        .HasColumnType("double precision");

                    b.Property<double>("CEActualChange")
                        .HasColumnType("double precision");

                    b.Property<double>("CEExpected")
                        .HasColumnType("double precision");

                    b.Property<double>("CEExpectedChange")
                        .HasColumnType("double precision");

                    b.Property<double>("CEResidual")
                        .HasColumnType("double precision");

                    b.Property<double>("CEResidualPct")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterStrike")
                        .HasColumnType("double precision");

                    b.Property<double>("CommonResidualPct")
                        .HasColumnType("double precision");

                    b.Property<double>("DirectionalResidualPct")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EndAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FutureChangeFrom0930")
                        .HasColumnType("double precision");

                    b.Property<int>("FuturesRollingDirection")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<double>("MaxQuoteAgeSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("ModeledWeeklyUnderlying")
                        .HasColumnType("double precision");

                    b.Property<double>("PEActual")
                        .HasColumnType("double precision");

                    b.Property<double>("PEActualChange")
                        .HasColumnType("double precision");

                    b.Property<double>("PEExpected")
                        .HasColumnType("double precision");

                    b.Property<double>("PEExpectedChange")
                        .HasColumnType("double precision");

                    b.Property<double>("PEResidual")
                        .HasColumnType("double precision");

                    b.Property<double>("PEResidualPct")
                        .HasColumnType("double precision");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("ResidualDelta")
                        .HasColumnType("double precision");

                    b.Property<int>("ResidualDirection")
                        .HasColumnType("integer");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("UnavailableReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Variant")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "BarSeq", "Variant")
                        .IsUnique();

                    b.HasIndex("SessionId", "Variant", "BarSeq");

                    b.ToTable("adaptive_option_residual_bars", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveOptionsSupplementalRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BarCeQuantity")
                        .HasColumnType("bigint");

                    b.Property<long?>("BarPeQuantity")
                        .HasColumnType("bigint");

                    b.Property<int>("BarSeq")
                        .HasColumnType("integer");

                    b.Property<double?>("CeActivityPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("CeDeltaIv")
                        .HasColumnType("double precision");

                    b.Property<double?>("CeIvEnd")
                        .HasColumnType("double precision");

                    b.Property<double?>("CeIvStart")
                        .HasColumnType("double precision");

                    b.Property<double?>("CeMicroDevTimeWeighted")
                        .HasColumnType("double precision");

                    b.Property<double?>("CeMidDelta")
                        .HasColumnType("double precision");

                    b.Property<double?>("CeMidEnd")
                        .HasColumnType("double precision");

                    b.Property<double?>("CeMidStart")
                        .HasColumnType("double precision");

                    b.Property<long?>("CeOfi")
                        .HasColumnType("bigint");

                    b.Property<long?>("CeOiDelta")
                        .HasColumnType("bigint");

                    b.Property<long?>("CeOiEnd")
                        .HasColumnType("bigint");

                    b.Property<long?>("CeOiStart")
                        .HasColumnType("bigint");

                    b.Property<string>("CePosition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("CenterStrike")
                        .HasColumnType("double precision");

                    b.Property<long>("DayCeVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("DayPeVolume")
                        .HasColumnType("bigint");

                    b.Property<double?>("DeltaSkew")
                        .HasColumnType("double precision");

                    b.Property<double?>("IvSkewEnd")
                        .HasColumnType("double precision");

                    b.Property<double?>("IvSkewStart")
                        .HasColumnType("double precision");

                    b.Property<string>("MetricsVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ObservationStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("PeActivityPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeDeltaIv")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeIvEnd")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeIvStart")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeMicroDevTimeWeighted")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeMidDelta")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeMidEnd")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeMidStart")
                        .HasColumnType("double precision");

                    b.Property<long?>("PeOfi")
                        .HasColumnType("bigint");

                    b.Property<long?>("PeOiDelta")
                        .HasColumnType("bigint");

                    b.Property<long?>("PeOiEnd")
                        .HasColumnType("bigint");

                    b.Property<long?>("PeOiStart")
                        .HasColumnType("bigint");

                    b.Property<string>("PePosition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("RollCeQuantity")
                        .HasColumnType("bigint");

                    b.Property<long?>("RollPeQuantity")
                        .HasColumnType("bigint");

                    b.Property<double?>("RollVolPcr")
                        .HasColumnType("double precision");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<double?>("StraddleDelta")
                        .HasColumnType("double precision");

                    b.Property<double?>("StraddleMidEnd")
                        .HasColumnType("double precision");

                    b.Property<double?>("StraddleMidStart")
                        .HasColumnType("double precision");

                    b.Property<int>("TokensObserved")
                        .HasColumnType("integer");

                    b.Property<string>("UnavailableReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UniverseTokenCount")
                        .HasColumnType("integer");

                    b.Property<double?>("VolPcr")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "BarSeq", "MetricsVersion")
                        .IsUnique();

                    b.ToTable("adaptive_options_supplemental_bars", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveProjectionHealthRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BarSeq")
                        .HasColumnType("integer");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Component", "Version", "BarSeq")
                        .IsUnique();

                    b.ToTable("adaptive_projection_health", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveResidualAnchorComponentRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ImpliedVolatility0930")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCenterStrike")
                        .HasColumnType("boolean");

                    b.Property<int>("LotSize")
                        .HasColumnType("integer");

                    b.Property<double>("Price0930")
                        .HasColumnType("double precision");

                    b.Property<double>("QuoteAgeSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("QuoteTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<double>("Strike")
                        .HasColumnType("double precision");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TradingSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Side", "Strike")
                        .IsUnique();

                    b.ToTable("adaptive_residual_anchor_components", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveRollingStateRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Efficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("ElapsedSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EndAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndBarSeq")
                        .HasColumnType("integer");

                    b.Property<double>("EndPrice")
                        .HasColumnType("double precision");

                    b.Property<long>("EnrichedBuyVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("EnrichedDelta")
                        .HasColumnType("bigint");

                    b.Property<int>("EnrichedDeltaDirection")
                        .HasColumnType("integer");

                    b.Property<double>("EnrichedDeltaRatio")
                        .HasColumnType("double precision");

                    b.Property<long>("EnrichedSellVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("EnrichedUnknownVolume")
                        .HasColumnType("bigint");

                    b.Property<double>("FallbackShare")
                        .HasColumnType("double precision");

                    b.Property<double>("High")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsStrong")
                        .HasColumnType("boolean");

                    b.Property<double>("Low")
                        .HasColumnType("double precision");

                    b.Property<long?>("OiChange")
                        .HasColumnType("bigint");

                    b.Property<double?>("OiChangePct")
                        .HasColumnType("double precision");

                    b.Property<long?>("OiEnd")
                        .HasColumnType("bigint");

                    b.Property<long?>("OiStart")
                        .HasColumnType("bigint");

                    b.Property<double>("PathLength")
                        .HasColumnType("double precision");

                    b.Property<int>("PriceDirection")
                        .HasColumnType("integer");

                    b.Property<double>("PriceDisplacement")
                        .HasColumnType("double precision");

                    b.Property<bool?>("PriceEnrichedDeltaAgree")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PriceStrictDeltaAgree")
                        .HasColumnType("boolean");

                    b.Property<double>("ReturnBps")
                        .HasColumnType("double precision");

                    b.Property<long?>("RollingEnrichedDeltaChange")
                        .HasColumnType("bigint");

                    b.Property<double?>("RollingOiChangePctChange")
                        .HasColumnType("double precision");

                    b.Property<long?>("RollingStrictAbsDeltaChange")
                        .HasColumnType("bigint");

                    b.Property<long?>("RollingStrictDeltaChange")
                        .HasColumnType("bigint");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<double>("SignedEfficiency")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("StartAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StartBarSeq")
                        .HasColumnType("integer");

                    b.Property<double>("StartPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("StrictBuyVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("StrictDelta")
                        .HasColumnType("bigint");

                    b.Property<int>("StrictDeltaDirection")
                        .HasColumnType("integer");

                    b.Property<double?>("StrictDeltaRatioClassified")
                        .HasColumnType("double precision");

                    b.Property<double>("StrictDeltaRatioTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("StrictDominanceEvolution")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("StrictQuoteCoverage")
                        .HasColumnType("double precision");

                    b.Property<long>("StrictSellVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("StrictUnknownVolume")
                        .HasColumnType("bigint");

                    b.Property<int?>("StrongBaseBarSeq")
                        .HasColumnType("integer");

                    b.Property<int>("TradeUpdates")
                        .HasColumnType("integer");

                    b.Property<double?>("VolumePerSecond")
                        .HasColumnType("double precision");

                    b.Property<int?>("Weak1BarSeq")
                        .HasColumnType("integer");

                    b.Property<int>("WeakeningSequence")
                        .HasColumnType("integer");

                    b.Property<int>("WindowBars")
                        .HasColumnType("integer");

                    b.Property<double>("WindowRange")
                        .HasColumnType("double precision");

                    b.Property<long>("WindowVolume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "EndAvailableAtUtc");

                    b.HasIndex("SessionId", "EndBarSeq")
                        .IsUnique();

                    b.ToTable("adaptive_rolling_states", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveScreenshotJobRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Caption")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("NextAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetBarSeq")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("TriggeredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"Kind\" = 0");

                    b.HasIndex("Status", "NextAttemptUtc");

                    b.HasIndex("SessionId", "Kind", "TargetBarSeq")
                        .IsUnique();

                    b.ToTable("adaptive_screenshot_jobs", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseBarVolume")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("BuildUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EstimatedFullDayVolume")
                        .HasColumnType("double precision");

                    b.Property<long?>("EstimatorInputOpeningVolume")
                        .HasColumnType("bigint");

                    b.Property<double>("EstimatorIntercept")
                        .HasColumnType("double precision");

                    b.Property<string>("EstimatorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("EstimatorSlope")
                        .HasColumnType("double precision");

                    b.Property<double?>("Future0930")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("FutureExpiry")
                        .HasColumnType("date");

                    b.Property<string>("FutureSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FutureToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsHistoricalSeed")
                        .HasColumnType("boolean");

                    b.Property<int>("LotSize")
                        .HasColumnType("integer");

                    b.Property<int?>("MedianOpeningSampleCount")
                        .HasColumnType("integer");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ObservationStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OpeningCoverageMinutes")
                        .HasColumnType("integer");

                    b.Property<long>("OpeningVolume")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OpeningWindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OpeningWindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OptionUniverseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResidualAnchorCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ResidualCenterStrike")
                        .HasColumnType("double precision");

                    b.Property<double>("RiskFreeRate")
                        .HasColumnType("double precision");

                    b.Property<int>("RollingWindowBars")
                        .HasColumnType("integer");

                    b.Property<long>("RollingWindowVolume")
                        .HasColumnType("bigint");

                    b.Property<int>("RoundingLots")
                        .HasColumnType("integer");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceCommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("StrongQuantile")
                        .HasColumnType("double precision");

                    b.Property<double?>("StrongThreshold")
                        .HasColumnType("double precision");

                    b.Property<int>("StrongThresholdPriorStateCount")
                        .HasColumnType("integer");

                    b.Property<double?>("SyntheticWeeklyUnderlying0930")
                        .HasColumnType("double precision");

                    b.Property<int>("TargetBarsPerDay")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.Property<bool>("UsesMedianOpeningFallback")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("WeeklyOptionExpiry")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TradeDate", "ModelVersion")
                        .IsUnique();

                    b.ToTable("adaptive_sessions", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveWeak2ObservationRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AtmResidualDirectionalPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("BandResidualDirectionalPct")
                        .HasColumnType("double precision");

                    b.Property<long?>("CEOiStrongBase")
                        .HasColumnType("bigint");

                    b.Property<long?>("CEOiTrigger")
                        .HasColumnType("bigint");

                    b.Property<double?>("EntryAsk")
                        .HasColumnType("double precision");

                    b.Property<double?>("EntryBid")
                        .HasColumnType("double precision");

                    b.Property<double?>("EntryQuoteLatencySeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("EntryQuoteTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ExitAsk")
                        .HasColumnType("double precision");

                    b.Property<double?>("ExitBid")
                        .HasColumnType("double precision");

                    b.Property<double?>("ExitLatencySeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("ExitTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<double?>("FuturesH5Move")
                        .HasColumnType("double precision");

                    b.Property<int>("H5TargetBarSeq")
                        .HasColumnType("integer");

                    b.Property<double?>("HoldingSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaePointsExecutableBid")
                        .HasColumnType("double precision");

                    b.Property<double?>("MfePointsExecutableBid")
                        .HasColumnType("double precision");

                    b.Property<bool?>("OiGatePassed")
                        .HasColumnType("boolean");

                    b.Property<int>("OldTrendDirection")
                        .HasColumnType("integer");

                    b.Property<int>("OptionSide")
                        .HasColumnType("integer");

                    b.Property<long?>("PEOiStrongBase")
                        .HasColumnType("bigint");

                    b.Property<long?>("PEOiTrigger")
                        .HasColumnType("bigint");

                    b.Property<long?>("PairOiChange")
                        .HasColumnType("bigint");

                    b.Property<double?>("PairOiChangePct")
                        .HasColumnType("double precision");

                    b.Property<long?>("PairOiStrongBase")
                        .HasColumnType("bigint");

                    b.Property<long?>("PairOiTrigger")
                        .HasColumnType("bigint");

                    b.Property<double?>("PnlPoints")
                        .HasColumnType("double precision");

                    b.Property<bool?>("ResidualSupportsReversalDiagnostic")
                        .HasColumnType("boolean");

                    b.Property<double?>("ReturnPct")
                        .HasColumnType("double precision");

                    b.Property<int>("ReversalDirection")
                        .HasColumnType("integer");

                    b.Property<string>("SelectionPolicy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("StrictNoTurnDiagnostic")
                        .HasColumnType("boolean");

                    b.Property<double?>("Strike")
                        .HasColumnType("double precision");

                    b.Property<int>("StrongBaseBarSeq")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TradingSymbol")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TriggerBarSeq")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TriggerTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UnavailableReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Weak1BarSeq")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Status");

                    b.HasIndex("SessionId", "TriggerBarSeq")
                        .IsUnique();

                    b.ToTable("adaptive_weak2_observations", (string)null);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveCommentaryEventRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveCommentaryNotificationJobRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveCommentaryEventRow", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveCommentaryRuntimeRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveFutureBarRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveFuturesSupplementalRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveObserverRuntimeRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveOptionBandBarRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveOptionResidualBarRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveOptionsSupplementalRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveProjectionHealthRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveResidualAnchorComponentRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveRollingStateRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveScreenshotJobRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NiftySignal.AdaptiveObserverData.AdaptiveWeak2ObservationRow", b =>
                {
                    b.HasOne("NiftySignal.AdaptiveObserverData.AdaptiveSessionStateRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
