// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiftySignal.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NiftySignal.Persistence.Migrations
{
    [DbContext(typeof(NiftySignalDbContext))]
    [Migration("20260908044057_WidenPaperTradeVersionColumns")]
    partial class WidenPaperTradeVersionColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NiftySignal.Domain.Entities.DataGap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastReason")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReconnectAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EndedAt");

                    b.ToTable("data_gaps", (string)null);
                });

            modelBuilder.Entity("NiftySignal.Domain.Entities.FlatTradeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("flattrade_session", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("NiftySignal.Domain.Entities.Instrument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("Exchange")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("InstrumentType")
                        .HasColumnType("integer");

                    b.Property<int>("LotSize")
                        .HasColumnType("integer");

                    b.Property<int>("OptionType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StrikePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("Subscribed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TradingSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "Token", "AsOfDate")
                        .IsUnique();

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("NiftySignal.Domain.Entities.KillSwitchState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EntriesEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("kill_switch_state", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntriesEnabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "migration-seed"
                        });
                });

            modelBuilder.Entity("NiftySignal.Domain.Entities.PaperTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<double>("EntryScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EntryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("ExitReason")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ExitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("GrossPnl")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("HasPartiallyBooked")
                        .HasColumnType("boolean");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("MaxAdverseExcursionPct")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxFavourableExcursionPct")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("NetPnl")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("PartialExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset?>("PartialExitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("RulesetVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ScoreWeightsVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TradingSymbol")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("VixAtEntry")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EntryTime");

                    b.HasIndex("ExitTime");

                    b.ToTable("paper_trades", (string)null);
                });

            modelBuilder.Entity("NiftySignal.Domain.Entities.ScoreSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("CompositeScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("CompositeScoreRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("CompositeScoreRawInstant")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DepthImbalanceRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("DepthImbalanceZ")
                        .HasColumnType("double precision");

                    b.Property<double?>("FuturesBasisRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("FuturesBasisZ")
                        .HasColumnType("double precision");

                    b.Property<double?>("GammaExposureRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("GammaExposureZ")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsWarmedUp")
                        .HasColumnType("boolean");

                    b.Property<double?>("IvSkewRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("IvSkewZ")
                        .HasColumnType("double precision");

                    b.Property<double?>("OiBuildupNetRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("OiBuildupNetZ")
                        .HasColumnType("double precision");

                    b.Property<double?>("PcrRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("PcrZ")
                        .HasColumnType("double precision");

                    b.Property<double?>("PriceMomentumRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("PriceMomentumZ")
                        .HasColumnType("double precision");

                    b.Property<double?>("SpotPrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("SpreadRatioRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("SpreadRatioZ")
                        .HasColumnType("double precision");

                    b.Property<double?>("VixChangeRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("VixChangeZ")
                        .HasColumnType("double precision");

                    b.Property<double?>("VolumePcrRaw")
                        .HasColumnType("double precision");

                    b.Property<double?>("VolumePcrZ")
                        .HasColumnType("double precision");

                    b.Property<string>("WeightSetVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComputedAt");

                    b.ToTable("score_snapshots", (string)null);
                });

            modelBuilder.Entity("NiftySignal.Domain.Entities.StrikeSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AskPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("BidPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Delta")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<double?>("Gamma")
                        .HasColumnType("double precision");

                    b.Property<double?>("ImpliedVolatility")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("MarkPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long?>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<int>("OptionType")
                        .HasColumnType("integer");

                    b.Property<double?>("PriceVsTheoretical")
                        .HasColumnType("double precision");

                    b.Property<double?>("Rho")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("SpreadAbs")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("SpreadPctOfMid")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("StrikePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<double?>("TheoreticalPrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("ThetaPerDay")
                        .HasColumnType("double precision");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("Vega")
                        .HasColumnType("double precision");

                    b.Property<long?>("VolumeDelta")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ComputedAt");

                    b.HasIndex("Token", "ComputedAt");

                    b.ToTable("strike_snapshots", (string)null);
                });

            modelBuilder.Entity("NiftySignal.Domain.Entities.Tick", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Exchange")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExchangeTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long?>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("Token", "ExchangeTimestamp");

                    b.ToTable("ticks", (string)null);
                });

            modelBuilder.Entity("NiftySignal.Domain.Entities.Tick", b =>
                {
                    b.OwnsOne("NiftySignal.Domain.ValueObjects.MarketDepth", "Depth", b1 =>
                        {
                            b1.Property<long>("TickId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Ask1Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("ask1_price");

                            b1.Property<long>("Ask1Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("ask1_qty");

                            b1.Property<decimal>("Ask2Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("ask2_price");

                            b1.Property<long>("Ask2Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("ask2_qty");

                            b1.Property<decimal>("Ask3Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("ask3_price");

                            b1.Property<long>("Ask3Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("ask3_qty");

                            b1.Property<decimal>("Ask4Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("ask4_price");

                            b1.Property<long>("Ask4Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("ask4_qty");

                            b1.Property<decimal>("Ask5Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("ask5_price");

                            b1.Property<long>("Ask5Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("ask5_qty");

                            b1.Property<decimal>("Bid1Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("bid1_price");

                            b1.Property<long>("Bid1Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("bid1_qty");

                            b1.Property<decimal>("Bid2Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("bid2_price");

                            b1.Property<long>("Bid2Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("bid2_qty");

                            b1.Property<decimal>("Bid3Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("bid3_price");

                            b1.Property<long>("Bid3Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("bid3_qty");

                            b1.Property<decimal>("Bid4Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("bid4_price");

                            b1.Property<long>("Bid4Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("bid4_qty");

                            b1.Property<decimal>("Bid5Price")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("bid5_price");

                            b1.Property<long>("Bid5Qty")
                                .HasColumnType("bigint")
                                .HasColumnName("bid5_qty");

                            b1.HasKey("TickId");

                            b1.ToTable("ticks");

                            b1.WithOwner()
                                .HasForeignKey("TickId");
                        });

                    b.Navigation("Depth");
                });
#pragma warning restore 612, 618
        }
    }
}
