// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiftySignal.VolumeBarData;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NiftySignal.VolumeBarData.Migrations
{
    [DbContext(typeof(VolumeBarDbContext))]
    [Migration("20260917071902_AddOrderFlowImbalance")]
    partial class AddOrderFlowImbalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NiftySignal.VolumeBarData.VolumeBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("BarIndex")
                        .HasColumnType("integer");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FutureCvdNet")
                        .HasColumnType("bigint");

                    b.Property<double?>("FutureDepthImbalance")
                        .HasColumnType("double precision");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<long?>("OpenInterestAtClose")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<double?>("OrderFlowImbalance")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("StartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<double?>("VwapAtClose")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BarIndex")
                        .IsUnique();

                    b.ToTable("VolumeBars");
                });
#pragma warning restore 612, 618
        }
    }
}
