// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiftySignal.VolumeBarData;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NiftySignal.VolumeBarData.Migrations
{
    [DbContext(typeof(VolumeBarDbContext))]
    [Migration("20260920144454_AddLivePaperTrades")]
    partial class AddLivePaperTrades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NiftySignal.VolumeBarData.LiveEntrySignalRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<int>("EntryBarIndex")
                        .HasColumnType("integer");

                    b.Property<double>("EntryPercentile")
                        .HasColumnType("double precision");

                    b.Property<double>("EntryScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EntryTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExitBarIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ExitReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExitTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "EntryBarIndex")
                        .IsUnique();

                    b.ToTable("LiveEntrySignals");
                });

            modelBuilder.Entity("NiftySignal.VolumeBarData.LiveOptionsScoreRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("BarIndex")
                        .HasColumnType("integer");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MaxPainConfirmPasses")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaxPainConfirmScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("Percentile")
                        .HasColumnType("double precision");

                    b.Property<double?>("RawScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("ScaledScore")
                        .HasColumnType("double precision");

                    b.Property<string>("SessionLeg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BarIndex")
                        .IsUnique();

                    b.ToTable("LiveOptionsScoreBars");
                });

            modelBuilder.Entity("NiftySignal.VolumeBarData.LivePaperTradeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<int>("EntryBarIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EntryDecisionTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<double>("EntryScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EntryTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExitBarIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ExitDecisionTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ExitReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExitTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<decimal>("StrikePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "EntryBarIndex")
                        .IsUnique();

                    b.ToTable("LivePaperTrades");
                });

            modelBuilder.Entity("NiftySignal.VolumeBarData.OptionAtmBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<double?>("AtmCallIv")
                        .HasColumnType("double precision");

                    b.Property<double?>("AtmIv")
                        .HasColumnType("double precision");

                    b.Property<double?>("AtmPutIv")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("AtmStrike")
                        .HasColumnType("numeric");

                    b.Property<int>("BarIndex")
                        .HasColumnType("integer");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SyntheticForward")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BarIndex")
                        .IsUnique();

                    b.ToTable("OptionAtmBars");
                });

            modelBuilder.Entity("NiftySignal.VolumeBarData.OptionBandFlowBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("BandWidth")
                        .HasColumnType("integer");

                    b.Property<int>("BarIndex")
                        .HasColumnType("integer");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CallNotionalVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PutNotionalVolume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BandWidth");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BandWidth", "BarIndex")
                        .IsUnique();

                    b.ToTable("OptionBandFlowBars");
                });

            modelBuilder.Entity("NiftySignal.VolumeBarData.OptionDepthBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("BandWidth")
                        .HasColumnType("integer");

                    b.Property<int>("BarIndex")
                        .HasColumnType("integer");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<double?>("CallAskQtyAvg")
                        .HasColumnType("double precision");

                    b.Property<double?>("CallBidQtyAvg")
                        .HasColumnType("double precision");

                    b.Property<double?>("CallTobAskQtyAvg")
                        .HasColumnType("double precision");

                    b.Property<double?>("CallTobBidQtyAvg")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("PutAskQtyAvg")
                        .HasColumnType("double precision");

                    b.Property<double?>("PutBidQtyAvg")
                        .HasColumnType("double precision");

                    b.Property<double?>("PutTobAskQtyAvg")
                        .HasColumnType("double precision");

                    b.Property<double?>("PutTobBidQtyAvg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BandWidth");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BandWidth", "BarIndex")
                        .IsUnique();

                    b.ToTable("OptionDepthBars");
                });

            modelBuilder.Entity("NiftySignal.VolumeBarData.OptionMaxPainBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("BarIndex")
                        .HasColumnType("integer");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("HighestOiStrike")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxPainStrike")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BarIndex")
                        .IsUnique();

                    b.ToTable("OptionMaxPainBars");
                });

            modelBuilder.Entity("NiftySignal.VolumeBarData.OptionOiBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("BandWidth")
                        .HasColumnType("integer");

                    b.Property<int>("BarIndex")
                        .HasColumnType("integer");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<double?>("BuildupNet")
                        .HasColumnType("double precision");

                    b.Property<decimal>("CallOiChangeNotional")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PutOiChangeNotional")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BandWidth");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BandWidth", "BarIndex")
                        .IsUnique();

                    b.ToTable("OptionOiBars");
                });

            modelBuilder.Entity("NiftySignal.VolumeBarData.OptionSkew25DeltaBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("BarIndex")
                        .HasColumnType("integer");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<double?>("Call25DeltaIv")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Call25DeltaStrike")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Put25DeltaIv")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Put25DeltaStrike")
                        .HasColumnType("numeric");

                    b.Property<double?>("SkewRatio")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("SyntheticForward")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BarIndex")
                        .IsUnique();

                    b.ToTable("OptionSkew25DeltaBars");
                });

            modelBuilder.Entity("NiftySignal.VolumeBarData.VolumeBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("BarIndex")
                        .HasColumnType("integer");

                    b.Property<long>("BarVolumeThreshold")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FutureCvdNet")
                        .HasColumnType("bigint");

                    b.Property<double?>("FutureDepthImbalance")
                        .HasColumnType("double precision");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric");

                    b.Property<long?>("OpenInterestAtClose")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric");

                    b.Property<double?>("OrderFlowImbalance")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("StartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TopOfBookImbalance")
                        .HasColumnType("double precision");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<double?>("VwapAtClose")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold");

                    b.HasIndex("AsOfDate", "BarVolumeThreshold", "BarIndex")
                        .IsUnique();

                    b.ToTable("VolumeBars");
                });
#pragma warning restore 612, 618
        }
    }
}
