// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiftySignal.BacktestData;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NiftySignal.BacktestData.Migrations
{
    [DbContext(typeof(BacktestAnalysisDbContext))]
    [Migration("20260912050752_AddFutureCvdProxyRollingNet")]
    partial class AddFutureCvdProxyRollingNet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NiftySignal.BacktestData.CadenceContext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("AtmStrikeByFuture")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AtmStrikeBySpot")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AtmStrikeBySyntheticForward")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureChangeForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureChangeFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureCloseFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<long?>("FutureCvdProxyCumulativeDay")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureCvdProxyNet15Min")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureCvdProxyNet5Min")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureCvdProxyThisCadence")
                        .HasColumnType("bigint");

                    b.Property<double?>("FutureDepthImbalanceFromLastCadence")
                        .HasColumnType("double precision");

                    b.Property<double?>("FutureDepthImbalanceMean15Min")
                        .HasColumnType("double precision");

                    b.Property<double?>("FutureDepthImbalanceMean5Min")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("FutureHighForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureHighFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureLowForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureLowFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<long?>("FutureOiChangeForDay")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureOiChangeFromLastKnown")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("FutureOpenForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureOpenFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<long?>("FutureOpenInterest")
                        .HasColumnType("bigint");

                    b.Property<double?>("FutureTotalAskQty")
                        .HasColumnType("double precision");

                    b.Property<double?>("FutureTotalBidQty")
                        .HasColumnType("double precision");

                    b.Property<long?>("FutureVolumeCumulativeDay")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureVolumeDeltaThisCadence")
                        .HasColumnType("bigint");

                    b.Property<double?>("FutureVwap")
                        .HasColumnType("double precision");

                    b.Property<double?>("HoursToExpiryCalendar")
                        .HasColumnType("double precision");

                    b.Property<double?>("HoursToExpiryTrading")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("NearestExpiryDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("SpotChangeForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotChangeFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotCloseFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotHighForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotHighFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotLowForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotLowFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotOpenForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotOpenFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<int>("TicksObservedFuture")
                        .HasColumnType("integer");

                    b.Property<int>("TicksObservedSpot")
                        .HasColumnType("integer");

                    b.Property<int>("TicksObservedVix")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VixChangeForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixChangeFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixCloseFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixHighForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixHighFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixLowForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixLowFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixOpenForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixOpenFromLastCadence")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("CadenceContexts");
                });
#pragma warning restore 612, 618
        }
    }
}
