// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiftySignal.BacktestData;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NiftySignal.BacktestData.Migrations
{
    [DbContext(typeof(BacktestAnalysisDbContext))]
    [Migration("20260912113034_AddOptionDepthImbalance")]
    partial class AddOptionDepthImbalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NiftySignal.BacktestData.CadenceContext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("AtmStrikeByFuture")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AtmStrikeBySpot")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AtmStrikeBySyntheticForward")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureChangeForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureChangeFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureCloseFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<long?>("FutureCvdProxyCumulativeDay")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureCvdProxyNet15Min")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureCvdProxyNet5Min")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureCvdProxyThisCadence")
                        .HasColumnType("bigint");

                    b.Property<double?>("FutureDepthImbalanceFromLastCadence")
                        .HasColumnType("double precision");

                    b.Property<double?>("FutureDepthImbalanceMean15Min")
                        .HasColumnType("double precision");

                    b.Property<double?>("FutureDepthImbalanceMean5Min")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("FutureHighForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureHighFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureLowForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureLowFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<long?>("FutureOiChangeForDay")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureOiChangeFromLastKnown")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("FutureOpenForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureOpenFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<long?>("FutureOpenInterest")
                        .HasColumnType("bigint");

                    b.Property<double?>("FutureTotalAskQty")
                        .HasColumnType("double precision");

                    b.Property<double?>("FutureTotalBidQty")
                        .HasColumnType("double precision");

                    b.Property<long?>("FutureVolumeCumulativeDay")
                        .HasColumnType("bigint");

                    b.Property<long?>("FutureVolumeDeltaThisCadence")
                        .HasColumnType("bigint");

                    b.Property<double?>("FutureVwap")
                        .HasColumnType("double precision");

                    b.Property<double?>("HoursToExpiryCalendar")
                        .HasColumnType("double precision");

                    b.Property<double?>("HoursToExpiryTrading")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("NearestExpiryDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("SpotChangeForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotChangeFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotCloseFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotHighForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotHighFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotLowForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotLowFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotOpenForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpotOpenFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<int>("TicksObservedFuture")
                        .HasColumnType("integer");

                    b.Property<int>("TicksObservedSpot")
                        .HasColumnType("integer");

                    b.Property<int>("TicksObservedVix")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VixChangeForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixChangeFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixCloseFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixHighForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixHighFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixLowForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixLowFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixOpenForDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VixOpenFromLastCadence")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("CadenceContexts");
                });

            modelBuilder.Entity("NiftySignal.BacktestData.StrikeBandCadenceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("BandDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CadenceContextId")
                        .HasColumnType("bigint");

                    b.Property<int>("CadenceMinutes")
                        .HasColumnType("integer");

                    b.Property<double?>("CallAvgIv")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("CallCvdProxyNotionalNet")
                        .HasColumnType("numeric");

                    b.Property<long?>("CallCvdProxyVolumeNet")
                        .HasColumnType("bigint");

                    b.Property<double?>("CallDepthImbalanceAvg")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("CallNotionalSum")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallOiChangeNotionalSum")
                        .HasColumnType("numeric");

                    b.Property<long?>("CallOiChangeSum")
                        .HasColumnType("bigint");

                    b.Property<int>("CallStrikeCount")
                        .HasColumnType("integer");

                    b.Property<long?>("CallVolumeSum")
                        .HasColumnType("bigint");

                    b.Property<int>("DaysToExpiry")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<double?>("PutAvgIv")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("PutCvdProxyNotionalNet")
                        .HasColumnType("numeric");

                    b.Property<long?>("PutCvdProxyVolumeNet")
                        .HasColumnType("bigint");

                    b.Property<double?>("PutDepthImbalanceAvg")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("PutNotionalSum")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutOiChangeNotionalSum")
                        .HasColumnType("numeric");

                    b.Property<long?>("PutOiChangeSum")
                        .HasColumnType("bigint");

                    b.Property<int>("PutStrikeCount")
                        .HasColumnType("integer");

                    b.Property<long?>("PutVolumeSum")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("CadenceContextId", "ExpiryDate", "BandDefinition", "CadenceMinutes")
                        .IsUnique();

                    b.ToTable("StrikeBandCadenceSnapshots");
                });

            modelBuilder.Entity("NiftySignal.BacktestData.StrikeCadenceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("AskPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BidPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("CadenceContextId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("CloseFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CvdProxyNotionalThisCadence")
                        .HasColumnType("numeric");

                    b.Property<long?>("CvdProxyVolumeThisCadence")
                        .HasColumnType("bigint");

                    b.Property<int>("DaysToExpiry")
                        .HasColumnType("integer");

                    b.Property<double?>("Delta")
                        .HasColumnType("double precision");

                    b.Property<double?>("DepthImbalanceFromLastCadence")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<double?>("Gamma")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("HighFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<double?>("ImpliedVolatility")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("LowFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarkPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarkPriceDelta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NotionalDelta")
                        .HasColumnType("numeric");

                    b.Property<int?>("OiBuildup")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OiChangeNotional")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OiNotional")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OpenFromLastCadence")
                        .HasColumnType("numeric");

                    b.Property<long?>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<long?>("OpenInterestDelta")
                        .HasColumnType("bigint");

                    b.Property<int>("OptionType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SpreadAbs")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpreadPctOfMid")
                        .HasColumnType("numeric");

                    b.Property<int>("StrikeOffsetFromAtm")
                        .HasColumnType("integer");

                    b.Property<decimal>("StrikePrice")
                        .HasColumnType("numeric");

                    b.Property<double?>("ThetaPerDay")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("TotalAskQty")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalBidQty")
                        .HasColumnType("double precision");

                    b.Property<double?>("Vega")
                        .HasColumnType("double precision");

                    b.Property<long?>("VolumeDelta")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("CadenceContextId", "ExpiryDate", "StrikePrice", "OptionType")
                        .IsUnique();

                    b.ToTable("StrikeCadenceSnapshots");
                });

            modelBuilder.Entity("NiftySignal.BacktestData.StrikeBandCadenceSnapshot", b =>
                {
                    b.HasOne("NiftySignal.BacktestData.CadenceContext", null)
                        .WithMany()
                        .HasForeignKey("CadenceContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NiftySignal.BacktestData.StrikeCadenceSnapshot", b =>
                {
                    b.HasOne("NiftySignal.BacktestData.CadenceContext", null)
                        .WithMany()
                        .HasForeignKey("CadenceContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
